services:
  backend:
    build: ./backend
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Taipei

  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Taipei
